# Note: values of keys denoting paths are resolved relative to the directory
# in which this file is located.
# The tokens `~` and `~user` are also replaced by the corresponding users's
# home directory.

docker-compose:

  # Path to compose file to be used, relative to `docker-dir`
  compose-file: "docker-compose.yml"
  docker-dir: "../../assets/docker/"

  build-environment:
    # TODO:
    # For now these settings are common to all `yagna` containers.
    # In future we may want to have nodes running different versions
    # of `yagna` in the test network.

    # binary-path: ...
    # deb-path: ...
    # branch: ...
    # commit-hash: ...
    # release-tag: ...
    artifacts:
      - name: "ya-runtime-vm"
        use-prerelease: true
        release-tag: "v0.3.0"

  compose-log-patterns:
    ethereum-mainnet: ".*Wallets supplied."
    ethereum-goerli: ".*Wallets supplied."
    ethereum-polygon: ".*Wallets supplied."


key-dir: "../../assets/keys"


web-root: "../../assets/web-root"


node-types:
  # Each node type is a collection of attributes common to a group of nodes.
  # Required attributes are "name" and "class".

  - name: "Requestor"
    class: "goth.runner.probe.RequestorProbe"

  - name: "Provider"
    class: "goth_tests.helpers.probe.ProviderProbe"
    mount:
      - read-only: "../../assets/provider/presets.json"
        destination: "/root/.local/share/ya-provider/presets.json"
      - read-only: "../../assets/provider/hardware.json"
        destination: "/root/.local/share/ya-provider/hardware.json"
    privileged-mode: True
    environment:
      - "IDLE_AGREEMENT_TIMEOUT=5s"
      - "DEBIT_NOTE_ACCEPTANCE_DEADLINE=8s"
      - "DEBIT_NOTE_INTERVAL=1s"

nodes:

  - name: "requestor"
    type: "Requestor"

  - name: "provider-1"
    type: "Provider"
    use-proxy: True
