[package]
name = "ya-utils-actix"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
time-dependent-tests = []

[dependencies]
actix = { version = "0.11", default-features = false }
anyhow = "^1.0"
chrono = "^0.4"
futures = "^0.3"
log = "0.4"

[dev-dependencies]
actix-rt = "2.2"
tokio = { version = "1", features = ["process", "signal"] }
