[package]
name = "ya-exe-dummy"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
actix = "0.9"
anyhow = "1.0"
futures = "0.3"
pretty_env_logger = "0.3"
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "0.2", features = ["time"] }

[dependencies.api]
version = "0.1"
package = "ya-exe-api"

[dependencies.serde]
version = "1.0"
features = ["derive"]
