[package]
name = "ya-utils-consent"
version = "0.1.0"
description = "Consent (allow/deny settings) service for Yagna"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
metrics = "0.12"
serde = "1"
serde_json = "1"
strum.workspace = true
promptly.workspace = true
parking_lot.workspace = true
ya-service-api.workspace = true
ya-service-api-interfaces.workspace = true
ya-utils-path = { path = "../path" }

[dev-dependencies]
env_logger = "0"
rand.workspace = true

[features]
require-consent = []