[package]
name = "gsb-http-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ya-service-bus = { version = "0.6.3" }

thiserror = "1.0.51"
serde = { version = "1.0.193", features = ["derive"] }
chrono = "0.4"
http = "1.0.0"
serde_json = "1.0.111"
tokio = { version = "1.35.0", features = ["full"] }
reqwest = { version = "0.11.23", features = ["json"] }
log = { version = "0.4.20", features = [] }
async-stream = "0.3.5"
futures = { version = "0.3", features = [] }