[package]
name = "ya-service-api"
version = "0.1.0"
description = "Interface for modules of Yagna service and CLI"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
actix = "0.8"  # TODO: migrate to 0.9
anyhow = "1.0"
futures = { version = "0.3", features = ['compat']}  # TODO: remove compat
lazy_static = "1.4"
prettytable-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
