[package]
name = "ya-utils-futures"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["time"] }
futures3 = { version = "0.3", features = ["compat"], package = "futures" }
