[package]
name = "ya-file-logging"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
flexi_logger = { version = "0.17", features = ["colors", "compress"] }
log = "0.4"
yansi = "0.5.0"

[features]
packet-trace-enable = []
default = []
