[package]
name = "ya-market-resolver"
version = "0.2.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-agreement-utils = "0.4"

asnom = { git = "https://github.com/dequbed/asnom.git" }
bigdecimal = "0.2"
chrono = "0.4"
log = "0.4"
nom = "2.0"
regex = "1"
semver = "0.11"
serde_json = "1.0.55"
thiserror = "1.0.20"

[dev-dependencies]
env_logger = "0.7"
