[package]
name = "ya-compile-time-utils"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
description = "Compile-time utilities"

[dependencies]
git-version = "0.3.4"
semver = "0.11.0"

[build-dependencies]
vergen = "3.1.0"
