[package]
name = "ya-compile-time-utils"
version = "0.1.3"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
homepage = "https://github.com/golemfactory/yagna/utils/compile-time-utils"
repository = "https://github.com/golemfactory/yagna"
license = "LGPL-3.0"
description = "Yagna Compile-time utilities"
keywords=["golem", "yagna", "compile", "compile-time"]

[dependencies]
git-version = "0.3.4"
metrics = "0.12"
semver = "0.11.0"

[build-dependencies]
vergen = "3.1.0"
