[package]
name = "ya-zksync-driver"
version = "0.2.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = []

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
bigdecimal = { version = "0.2" }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
hex = "0.4"
lazy_static = "1.4"
log = "0.4.8"
maplit = "1.0"
metrics-macros = "=0.1.0-alpha.5"
num-bigint = { version = "0.3", features = ["serde"] }
rlp = "0.5"
serde = "1.0"
serde_json = "^1.0"
tiny-keccak = "1.4.2"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
zksync = { git = "https://github.com/matter-labs/zksync", rev = "0e28e238f71b3be128e4a760b0147e7c62d8dee5"}
zksync_eth_signer = { git = "https://github.com/matter-labs/zksync", rev = "0e28e238f71b3be128e4a760b0147e7c62d8dee5"}

## yagna dependencies
ya-payment-driver = "0.2"
ya-client-model = "0.4"
ya-service-api = { version = "0.1.1", features=["with-awc"], path="../../serv-api" }
ya-service-api-interfaces = "0.1"
ya-utils-futures = "0.1"
ya-utils-networking = "0.1"

[dev-dependencies]
actix-rt = "1.0"
dotenv = "0.15.0"
env_logger = "0.7.1"
structopt = "0.3"
