[package]
name = "ya-diesel-utils"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
description="Utilities helping using diesel."

[lib]
proc-macro = true

[dependencies]
syn = "1.0.48"
diesel = { version = "1.4", features = ["chrono", "sqlite", "r2d2"] }
proc-macro2 = "1.0"
quote = "1.0"
