[package]
name = "tokio-process-ns"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio= { version = "1.6", features=["process"] }

[target.'cfg(target_os="linux")'.dependencies]
libc= "0.2"
nix="0.22.0"

[dev-dependencies]
tokio= { version = "1.6", features=["process", "rt-multi-thread", "macros"] }
