name: Definition of Done
on:
  pull_request:
    types: [opened, edited]

jobs:
  check-dod:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoD
        uses: platisd/definition-of-done@master
        with:
          dod_yaml: 'dod.yml'
          github_token: ${{ secrets.CORE_BOARD_ACTIONS_TOKEN }}
